server:
  port: 7070


security:
  oauth2:
    resource:
      userInfoUri: xx

okta:
  oauth2:
    clientId: xx
    clientSecret: xx
    issuer: xx
    audience: api://default
    accessTokenUri: xx
    userAuthorizationUri: xx
