

server:
  port: 7070


security:
  oauth2:
    resource:
      userInfoUri: https://dev-648083.oktapreview.com/oauth2/default/v1/userinfo

okta:
  oauth2:
    clientId: 0oagr4swilP6cGfxC0h7
    clientSecret: g7DPLf1hNIiCEqmeZmxyfOjmyCpxyzw6tI1p0Blf
    issuer: https://dev-648083.oktapreview.com/oauth2/default
    audience: api://default
    accessTokenUri: https://dev-648083.oktapreview.com/oauth2/default/v1/token
    userAuthorizationUri: https://dev-648083.oktapreview.com/oauth2/default/v1/authorize