

server:
  port: 7070


security:
  oauth2:
    resource:
      userInfoUri: https://{your_okta_url}/oauth2/default/v1/userinfo

okta:
  oauth2:
    clientId: {your_client_id}
    clientSecret: {your_client_secret}
    issuer: https://{your_okta_url}/oauth2/default
    audience: api://default
    accessTokenUri: https://{your_okta_url}/oauth2/default/v1/token
    userAuthorizationUri: https://{your_okta_url}/oauth2/default/v1/authorize
